"""empty message

Revision ID: ad20bd5d7464
Revises: 4fa3bf86264a
Create Date: 2026-04-11 01:39:52.145909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad20bd5d7464'
down_revision = '4fa3bf86264a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('login', sa.Text(), nullable=False))
        batch_op.drop_column('text')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=300), nullable=False))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.drop_column('login')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
